%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: /Users/kiran/Documents/Projects/ICLR/Avionics/Ricardo_OS/Python_backend/profile.txt
%
% Auto-generated by MATLAB on 12-Sep-2021 00:48:18

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 2);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ":";

% Specify column names and types
opts.VariableNames = ["cat", "time"];
opts.VariableTypes = ["categorical", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "cat", "EmptyFieldRule", "auto");

% Import the data
profile1 = readtable("/Users/kiran/Documents/Projects/ICLR/Avionics/Ricardo_OS/Python_backend/profiler/profile.txt", opts);


%% Clear temporary variables
clear opts

profile_table.imu = table2array(profile1(profile1.cat=='imu',2))
profile_table.gps = table2array(profile1(profile1.cat=='gps',2))
profile_table.baro = table2array(profile1(profile1.cat=='baro',2))
profile_table.batt = table2array(profile1(profile1.cat=='batt',2))


figure
hold on

plot(profile_table.imu/1000)
plot(profile_table.gps/1000)
plot(profile_table.baro/1000)
plot(profile_table.batt/1000)


legend('imu','gps','baro','batt')